### ISSUE TITLE
Command line parameter

### ISSUE THREAD

**Issue by askary94** [ststeiger/procyon#2]
Hello.
I have a feature request. Have the ability to decompile a apk file and save all the source code from command line.
Thanks

**Comment by ststeiger** [comment]
How about: 
http://www.decompiler.com/

**Comment by askary94** [comment]
Hello @ststeiger 
Thank you for your feedback.
I formerly using ```jadx``` but missing many classes. so I want to work with Procyon for decompiling apk file to java's Source code through CommandLine (or Terminal). Researched in Github but not see any help for this.
Is it possible to work with Procyon through the ```Terminal``` for get SourceCode?

**Comment by ststeiger** [comment]
As it's stated in the README, procyon is a compiler/decompiler FRAMEWORK. 

You are interested in the decompiler in 
https://bitbucket.org/mstrobel/procyon/src/default/Procyon.CompilerTools/

You can get that from [Maven Repository](https://mvnrepository.com/artifact/org.bitbucket.mstrobel/procyon-compilertools).

If you click at [used by artifacts](https://mvnrepository.com/artifact/org.bitbucket.mstrobel/procyon-compilertools/usages), you basically get a list of decompilers based on procyon.


### As for the Procyon.CompilerTools: 

There's a nice list for the procyon-compilertools at [frontbackend.com](https://frontbackend.com/maven/artifact/org.bitbucket.mstrobel/procyon-compilertools/)

There you see that the latest version is [0.5.36](https://frontbackend.com/maven/artifact/org.bitbucket.mstrobel/procyon-compilertools/0.5.36).

Under "Artifact details" it has "Files | Browse". 
Click on browse and you get the maven directory for [0.5.36](https://repo1.maven.org/maven2/org/bitbucket/mstrobel/procyon-compilertools/0.5.36/).

There, download [procyon-compilertools-0.5.36.jar](https://repo1.maven.org/maven2/org/bitbucket/mstrobel/procyon-compilertools/0.5.36/procyon-compilertools-0.5.36.jar).

After download, execute with 
```
chmod +x ./procyon-compilertools-0.5.36.jar
java -jar ./procyon-compilertools-0.5.36.jar <your arguments here>
```

**Comment by askary94** [comment]
Thank you for your response.
