### ISSUE TITLE
The wiki page is unavailable

### ISSUE THREAD

**Issue by jadsonjs** [ststeiger/procyon#3]
First of all, very good tool, congratulations. 

But the wiki page in unavailable on bitbucket.  https://bitbucket.org/mstrobel/procyon/wiki/Java%20Decompiler

Do you have a new wiki page that show how to use procyon decompiler programmatically to decompile a .class file?

Thank you.

**Comment by ststeiger** [comment]
Ask Mike Strobel for that:
https://github.com/mstrobel
