### ISSUE TITLE
Stuck when decompiling class CustomWorldSettingsFinal

### ISSUE THREAD

**Issue by KATu2011** [ststeiger/procyon#5]
At the decompile net/minecraft/server/v1_8_R3/CustomWorldSettingsFinal task and it stuck 1,5 hour + doesn't continue, but the class file CustomWorldSettingsFinal.class is just 4KB(i extract from jar file), please fix :(

Image:
![Capture](https://github.com/ststeiger/procyon/assets/135348369/a8438856-1bf2-4b5b-b7e9-e7dfde0480c7)
![Capture1](https://github.com/ststeiger/procyon/assets/135348369/6cf192c9-0265-4eaa-a5f1-91cbfbd98f00)

**Comment by ststeiger** [comment]
This is not the proper repository. 
Please go to https://github.com/mstrobel/procyon
This an old copy that i still need.
